### ISSUE TITLE
Missing tomo_display.sav

### ISSUE THREAD

**Issue by hueyke** [CARS-UChicago/IDL_Tomography#2]
Please generate and add `tomo_display.sav` to the repository for users who don't have an IDL license. Thank you!

**Comment by MarkRivers** [comment]
tomo_display.sav is 11MB and can change frequently, so I don't think it should be part of the repository.

The documentation installation page here has a link where you can download a zip file that contains tomo_display.sav and the required .dll and .so files:
https://cars-uchicago.github.io/IDL_Tomography/installation.html

That link is here:
https://cars.uchicago.edu/data/tomography/tomo_display/tomo_display.zip

**Comment by hueyke** [comment]
Thank you for your explanation!
